refactor: reduce number of forks on primary codepaths
Drop $() in primary non-debug non-error operations wherever possible:
Use var assignments, put extra debug message formatting behind normalized
(non-)emtpy DEBUG var check.

This greatly reduces the number of subhsell forks, speeding things up a bit.

diff --git a/app2unit b/app2unit
--- a/app2unit
+++ b/app2unit
@@ -3,10 +3,15 @@
 N='
 '
 OIFS=$IFS
-RSEP=$(printf '%b' '\036')
-USEP=$(printf '%b' '\037')
 TERMINAL_HANDLER=xdg-terminal-exec
 SELF_NAME=${0##*/}
+{
+	read -r RSEP
+	read -r USEP
+	read -r CR
+} <<- EOF
+	$(printf '%b\n' '\036' '\037' '\r')
+EOF
 
 # Treat non-zero exit status from simple commands as an error
 # Treat unset variables as errors when performing parameter expansion
@@ -14,7 +19,7 @@ SELF_NAME=${0##*/}
 set -euf
 
 shcat() {
-	while IFS='' read -r line; do
+	while IFS= read -r line; do
 		printf '%s\n' "$line"
 	done
 }
@@ -101,7 +106,7 @@ help() {
 		  -d description
 		    Set/override unit description. By default description is generated from
 		    Entry's "Name=" and "GenericName=" keys.
-		
+
 		  -p Property=value
 		    Set additional properties for unit.
 
@@ -225,15 +230,17 @@ check_bool() {
 
 # Utility function to print debug messages to stderr (or not)
 if check_bool "${DEBUG-0}"; then
+	DEBUG=true
 	debug() {
 		# print each arg at new line, prefix each printed line with 'D: '
-		while IFS='' read -r debug_line; do
+		while IFS= read -r debug_line; do
 			printf 'D: %s\n' "$debug_line"
 		done <<- EOF >&2
 			$(printf '%s\n' "$@")
 		EOF
 	}
 else
+	DEBUG=
 	debug() { :; }
 fi
 
@@ -263,9 +270,10 @@ replace() {
 
 normpath() {
 	# lightly normalize paths for comparison purposes
+	# write to NORMALIZED_PATH var
 	case "$1" in
 	/*) path_result= ;;
-	*) path_result=$(pwd) ;;
+	*) path_result=${PWD} ;;
 	esac
 	IFS='/'
 	for path_item in $1; do
@@ -288,7 +296,7 @@ normpath() {
 	done
 	IFS=$OIFS
 	debug "before normpath: $1" " after normpath: $path_result"
-	printf '%s' "$path_result"
+	NORMALIZED_PATH=$path_result
 }
 # Mask IFS change
 alias normpath='IFS= normpath'
@@ -296,7 +304,7 @@ alias normpath='IFS= normpath'
 make_paths() {
 	# constructs normalized APPLICATIONS_DIRS
 	IFS=':'
-	APPLICATIONS_DIRS=''
+	APPLICATIONS_DIRS=
 	# Populate list of directories to search for entries in, in descending order of preference
 	for dir in ${XDG_DATA_HOME:-${HOME}/.local/share}${IFS}${XDG_DATA_DIRS:-/usr/local/share:/usr/share}; do
 		case "$dir" in
@@ -307,7 +315,8 @@ make_paths() {
 			;;
 		esac
 		# Normalise base path and append the data subdirectory with a trailing '/'
-		APPLICATIONS_DIRS=${APPLICATIONS_DIRS:+${APPLICATIONS_DIRS}${IFS}}$(normpath "${dir}")/applications/
+		normpath "${dir}"
+		APPLICATIONS_DIRS=${APPLICATIONS_DIRS:+${APPLICATIONS_DIRS}${IFS}}${NORMALIZED_PATH}/applications/
 	done
 	IFS=$OIFS
 }
@@ -316,7 +325,8 @@ alias make_paths='IFS= make_paths'
 
 find_entry() {
 	# finds entry by ID
-	ENTRY_ID=$1
+	# writes to FOUND_ENTRY_PATH var
+	fe_find_entry_id=$1
 
 	# start assembling find args
 	set --
@@ -325,42 +335,42 @@ find_entry() {
 
 	# Append application directory paths to be searched
 	IFS=':'
-	for directory in $APPLICATIONS_DIRS; do
+	for fe_directory in $APPLICATIONS_DIRS; do
 		# Append '.' to delimit start of Entry ID
-		set -- "$@" "$directory".
+		set -- "$@" "$fe_directory".
 	done
 
 	# Find all files
 	set -- "$@" -type f
 
 	# Append path conditions per directory
-	or_arg=''
-	for directory in $APPLICATIONS_DIRS; do
+	or_arg=
+	for fe_directory in $APPLICATIONS_DIRS; do
 		# Match full path with proper first character of Entry ID and .desktop extension
 		# Reject paths with invalid characters in Entry ID
-		set -- "$@" ${or_arg} '(' -path "$directory"'./[a-zA-Z0-9_]*.desktop' ! -path "$directory"'./*[^a-zA-Z0-9_./-]*' ')'
+		set -- "$@" ${or_arg} '(' -path "$fe_directory"'./[a-zA-Z0-9_]*.desktop' ! -path "$fe_directory"'./*[^a-zA-Z0-9_./-]*' ')'
 		or_arg='-o'
 	done
 
 	# iterate over found paths
 	IFS=$OIFS
-	while read -r entry_path <&3; do
+	while read -r fe_entry_path <&3; do
 		# raw drop or parse and separate data dir path from entry
-		case "$entry_path" in
+		case "$fe_entry_path" in
 		# empties, just in case
 		'' | */./) continue ;;
 		# subdir, also replace / with -
 		*/./*/*)
-			replace "${entry_path#*/./}" "/" "-"
-			entry_id=$REPLACED_STR
+			replace "${fe_entry_path#*/./}" "/" "-"
+			fe_entry_id=$REPLACED_STR
 			;;
 		# normal separation
-		*/./*) entry_id=${entry_path#*/./} ;;
+		*/./*) fe_entry_id=${fe_entry_path#*/./} ;;
 		esac
 		# check ID
-		case "$entry_id" in
-		"$ENTRY_ID")
-			printf '%s' "$entry_path"
+		case "$fe_entry_id" in
+		"$fe_find_entry_id")
+			FOUND_ENTRY_PATH=$fe_entry_path
 			return 0
 			;;
 		esac
@@ -368,7 +378,7 @@ find_entry() {
 		$(find -L "$@" 2> /dev/null)
 	EOP
 
-	error "Could not find entry '$ENTRY_ID'!"
+	error "Could not find entry '$fe_find_entry_id'!"
 	return 1
 }
 # Mask IFS change
@@ -418,7 +428,7 @@ de_expand_str() {
 			debug "expander substituted tab"
 			;;
 		r*)
-			EXPANDED_STR=${EXPANDED_STR}$(printf '%b' '\r')
+			EXPANDED_STR=${EXPANDED_STR}${CR}
 			exp_remainder=${exp_remainder#?}
 			debug "expander substituted caret return"
 			;;
@@ -562,6 +572,8 @@ de_tokenize_exec() {
 		return 1
 		;;
 	esac
+
+	[ -n "$DEBUG" ] || return 0
 	# shellcheck disable=SC2086
 	debug "tokenizer ended:" "$(
 		IFS=$USEP
@@ -573,9 +585,9 @@ de_inject_fields() {
 	# Operates on argument array and $EXEC_RSEP_USEP from entry
 	# modifies $EXEC_RSEP_USEP according to args/fields
 	# no arguments, erase fields from $EXEC_RSEP_USEP
-	exec_usep=''
+	exec_usep=
 	fu_found=false
-	exec_iter_usep=''
+	exec_iter_usep=
 	IFS=$USEP
 	for arg in $EXEC_RSEP_USEP; do
 		case "$arg" in
@@ -617,7 +629,8 @@ de_inject_fields() {
 				;;
 			*[!%]'%u'* | '%u'*)
 				for carg in "$@"; do
-					carg=$(urlencode "$carg")
+					urlencode "$carg"
+					carg=$URLENCODED_STRING
 					replace "$arg" "%u" "$carg"
 					carg=$REPLACED_STR
 					debug "injector adding '$arg' iteration as '$carg'"
@@ -628,7 +641,8 @@ de_inject_fields() {
 				;;
 			'%U')
 				for carg in "$@"; do
-					carg=$(urlencode "$carg")
+					urlencode "$carg"
+					carg=$URLENCODED_STRING
 					debug "injector extending '$arg' with '$carg'"
 					exec_usep=${exec_usep}${exec_usep:+$USEP}${carg}
 				done
@@ -674,7 +688,7 @@ de_inject_fields() {
 	done
 	# fill EXEC_RSEP_USEP with argument iterations
 	if [ -n "$exec_iter_usep" ]; then
-		EXEC_RSEP_USEP=''
+		EXEC_RSEP_USEP=
 		for arg in $exec_iter_usep; do
 			replace "$exec_usep" "%%__ITER__%%" "$arg"
 			cmd=$REPLACED_STR
@@ -1033,36 +1047,39 @@ validate_action_id() {
 }
 
 urlencode() {
-	string=$1
-	case "$string" in
+	# pretty dumb urlencode
+	# writes to URLENCODED_STRING var
+	ue_string=$1
+	case "$ue_string" in
 	# assuming already url
 	*[a-zA-Z0-9_-]://*)
-		echo "$string"
+		URLENCODED_STRING=$ue_string
 		return
 		;;
 	# assuming absolute path
 	/*) true ;;
 	# assuming relative path
-	*) string=$(pwd)/$string ;;
+	*) ue_string=${PWD}/$ue_string ;;
 	esac
 
-	printf '%s' 'file://'
+	URLENCODED_STRING='file://'
 
-	case "$string" in
+	case "$ue_string" in
 	# if contains extra chars, encode
 	*[!._~0-9A-Za-z/-]*)
-		while [ -n "$string" ]; do
-			right=${string#?}
-			char=${string%"$right"}
-			debug "urlencode string $string" "urlencode right $right" "urlencode char $char"
-			case $char in
-			[._~0-9A-Za-z/-]) printf '%s' "$char" ;;
-			*) printf '%%%02x' "'$char" ;;
+		while [ -n "$ue_string" ]; do
+			ue_right=${ue_string#?}
+			ue_char=${ue_string%"$ue_right"}
+			debug "urlencode string $ue_string" "urlencode right $ue_right" "urlencode char $ue_char"
+			case $ue_char in
+			[._~0-9A-Za-z/-]) URLENCODED_STRING=${URLENCODED_STRING}$ue_char ;;
+			*) URLENCODED_STRING=${URLENCODED_STRING}$(printf '%%%02x' "'$ue_char") ;;
 			esac
-			string=$right
+			ue_string=$ue_right
 		done
 		;;
-	*) printf '%s' "$string" ;;
+	# no extra chars, append as is
+	*) URLENCODED_STRING=${URLENCODED_STRING}$ue_string ;;
 	esac
 }
 
@@ -1202,8 +1219,8 @@ systemd_run() {
 		out)
 			set -- --property=StandardOutput=null "$@"
 			# unsilence stderr if it is inheriting
-			dso=''
-			dse=''
+			dso=
+			dse=
 			while IFS='=' read -r key value; do
 				case "$key" in
 				DefaultStandardOutput) dso=$value ;;
@@ -1224,7 +1241,7 @@ systemd_run() {
 		;;
 	esac
 
-	debug "systemd run" "$(printf '  >%s<\n' systemd-run "$@")"
+	[ -z "$DEBUG" ] || debug "systemd run" "$(printf '  >%s<\n' systemd-run "$@")"
 
 	# print args in test mode
 	case "$TEST_MODE" in
@@ -1252,11 +1269,11 @@ parse_main_arg() {
 	# fills some of global variables depending on main arg $1
 	MAIN_ARG=$1
 
-	ENTRY_ID=''
-	ENTRY_ACTION=''
-	ENTRY_PATH=''
-	EXEC_NAME=''
-	EXEC_PATH=''
+	ENTRY_ID=
+	ENTRY_ACTION=
+	ENTRY_PATH=
+	EXEC_NAME=
+	EXEC_PATH=
 
 	case "$MAIN_ARG" in
 	'')
@@ -1270,7 +1287,7 @@ parse_main_arg() {
 		;;
 	*.desktop)
 		ENTRY_ID=$MAIN_ARG
-		ENTRY_ACTION=''
+		ENTRY_ACTION=
 		;;
 	esac
 	debug "ENTRY_ID: $ENTRY_ID" "ENTRY_ACTION: $ENTRY_ACTION"
@@ -1338,8 +1355,9 @@ check_terminal_handler() {
 }
 
 get_mime() {
-	# prints mime type of file or url
-	mime=
+	# gets mime type of file or url
+	# writes to MIME var
+	f_mime=
 	case "$1" in
 	[a-zA-Z]*:*)
 		IFS=':' read -r scheme _rest <<- EOF
@@ -1349,35 +1367,34 @@ get_mime() {
 		case "$scheme" in
 		*[!a-zA-Z0-9+.-]*)
 			debug "not a valid scheme '$scheme', assuming file"
-			mime=$(xdg-mime query filetype "$1")
+			f_mime=$(xdg-mime query filetype "$1")
 			;;
-		*) mime=x-scheme-handler/$scheme ;;
+		*) f_mime=x-scheme-handler/$scheme ;;
 		esac
 		;;
-	*) mime=$(xdg-mime query filetype "$1") ;;
+	*) f_mime=$(xdg-mime query filetype "$1") ;;
 	esac
 
-	case "$mime" in
+	case "$f_mime" in
 	'' | 'x-scheme-handler/')
 		error "Could not query mime type for '$1'"
 		return 1
 		;;
 	*)
-		debug "got mime '$mime' for '$1'"
-		echo "$mime"
-		return 0
+		debug "got mime '$f_mime' for '$1'"
+		MIME=$f_mime
 		;;
 	esac
 }
 
 get_assoc() {
-	# prints file association for mime type
-	assoc=$(xdg-mime query default "$1")
-	case "$assoc" in
+	# gets file association for mime type
+	# writes to ASSOC var
+	f_assoc=$(xdg-mime query default "$1")
+	case "$f_assoc" in
 	?*.desktop)
-		debug "got association '$assoc' for mime '$1'"
-		echo "$assoc"
-		return 0
+		debug "got association '$f_assoc' for mime '$1'"
+		ASSOC=$f_assoc
 		;;
 	*)
 		error "Could not query association for mime '$1'"
@@ -1388,31 +1405,32 @@ get_assoc() {
 
 ########################
 
-debug "initial args:" "$(printf '  >%s<\n' "$@")"
+[ -z "$DEBUG" ] || debug "initial args:" "$(printf '  >%s<\n' "$@")"
 
-EXEC_NAME=''
-EXEC_PATH=''
-EXEC_RSEP_USEP=''
-ENTRY_PATH=''
-ENTRY_ID=''
-ENTRY_TYPE=''
-ENTRY_URL=''
-ENTRY_COMMENT=''
-ENTRY_NAME=''
-ENTRY_ICON=''
-ENTRY_WORKDIR=''
-UNIT_DESCRIPTION=''
-UNIT_ID=''
-UNIT_APP_SUBSTRING=''
-UNIT_PROPERTIES=''
+EXEC_NAME=
+EXEC_PATH=
+EXEC_RSEP_USEP=
+ENTRY_PATH=
+ENTRY_ID=
+ENTRY_TYPE=
+ENTRY_URL=
+ENTRY_COMMENT=
+ENTRY_NAME=
+ENTRY_ICON=
+ENTRY_WORKDIR=
+UNIT_DESCRIPTION=
+UNIT_ID=
+UNIT_APP_SUBSTRING=
+UNIT_PROPERTIES=
+NORMALIZED_PATH=
 
-SILENT=''
+SILENT=
 TEST_MODE=false
 
 # vars for expander, tokenizer, injector output
-EXPANDED_STR=''
-EXEC_USEP=''
-REPLACED_STR=''
+EXPANDED_STR=
+EXEC_USEP=
+REPLACED_STR=
 
 UNIT_TYPE=${APP2UNIT_TYPE:-scope}
 case "$UNIT_TYPE" in
@@ -1424,7 +1442,7 @@ service | scope) true ;;
 esac
 
 # deal with unit slice choices and default
-UNIT_SLICE_ID=''
+UNIT_SLICE_ID=
 UNIT_SLICE_CHOICES=${APP2UNIT_SLICES:-"a=app.slice b=background.slice s=session.slice"}
 for choice in $UNIT_SLICE_CHOICES; do
 	debug "evaluating slice choice '$choice'"
@@ -1747,8 +1765,10 @@ if [ "$OPENER_MODE" = "true" ]; then
 	MAIN_ARG=
 	# determine if file or URL, get associations for MAIN_ARG
 	for arg in "$@"; do
-		mime=$(get_mime "$arg")
-		assoc=$(get_assoc "$mime")
+		get_mime "$arg"
+		mime=$MIME
+		get_assoc "$mime"
+		assoc=$ASSOC
 		if [ -z "$MAIN_ARG" ]; then
 			debug "setting MAIN_ARG from association for '$arg': '$assoc'"
 			MAIN_ARG=$assoc
@@ -1769,9 +1789,9 @@ elif [ "$FUZZEL_COMPAT" = "true" ]; then
 		error "Executable not found: '$1'"
 		exit 1
 	fi
-	EXEC_RSEP_USEP=$(
-		printf "%s${USEP}" "$@"
-	)
+	for item in "$@"; do
+		EXEC_RSEP_USEP=${EXEC_RSEP_USEP}${item}${USEP}
+	done
 	EXEC_RSEP_USEP=${EXEC_RSEP_USEP%"$USEP"}
 elif [ "$#" -eq "0" ] && [ "$TERMINAL" = "true" ]; then
 	# special case for launching just terminal
@@ -1791,12 +1811,13 @@ elif [ "$#" -eq "0" ] && [ "$TERMINAL" = "true" ]; then
 		# cmd after newline, fill exec array right away
 		EXEC_RSEP_USEP=${path_and_cmd#*"$N"}
 		# shellcheck disable=SC2086
-		debug "initial args:" "$(printf '  >%s<\n' "$@")"
-		# shellcheck disable=SC2086
-		debug "replaced MAIN_ARG with '$MAIN_ARG'" "populated EXEC_RSEP_USEP with:" "$(
-			IFS=$USEP
-			printf '  > %s\n' $EXEC_RSEP_USEP
-		)"
+		[ -z "$DEBUG" ] || debug "initial args:" "$(printf '  >%s<\n' "$@")" \
+			"replaced MAIN_ARG with '$MAIN_ARG'" \
+			"populated EXEC_RSEP_USEP with:" \
+			"$(
+				IFS=$USEP
+				printf '  > %s\n' $EXEC_RSEP_USEP
+			)"
 	else
 		# issue a warning to stderr
 		{
@@ -1816,7 +1837,8 @@ parse_main_arg "$MAIN_ARG"
 if [ -n "$ENTRY_PATH" ]; then
 	# reverse-deduce and correct Entry ID against applications dirs
 	make_paths
-	ENTRY_PATH=$(normpath "$ENTRY_PATH")
+	normpath "$ENTRY_PATH"
+	ENTRY_PATH=${NORMALIZED_PATH}
 	IFS=':'
 	for dir in $APPLICATIONS_DIRS; do
 		if [ "$ENTRY_PATH" != "${ENTRY_PATH#"$dir"}" ]; then
@@ -1840,7 +1862,8 @@ if [ -n "$ENTRY_PATH" ]; then
 	IFS=$OIFS
 elif [ -n "$ENTRY_ID" ]; then
 	make_paths
-	ENTRY_PATH=$(find_entry "$ENTRY_ID")
+	find_entry "$ENTRY_ID"
+	ENTRY_PATH=$FOUND_ENTRY_PATH
 fi
 
 # read and parse entry, fill ENTRY_* vars and EXEC_RSEP_USEP
@@ -1851,14 +1874,17 @@ fi
 # handle Link type URL
 if [ -n "$ENTRY_URL" ]; then
 	debug "re-parsing for Link entry URL: $ENTRY_URL"
-	mime=$(get_mime "$ENTRY_URL")
-	assoc=$(get_assoc "$mime")
+	get_mime "$ENTRY_URL"
+	mime=$MIME
+	get_assoc "$mime"
+	assoc=$ASSOC
 	# replace initial vars and arg
 	ENTRY_ID=$assoc
 	set -- "$ENTRY_URL"
 	ENTRY_URL=
 	# re-parse new entry
-	ENTRY_PATH=$(find_entry "$ENTRY_ID")
+	find_entry "$ENTRY_ID"
+	ENTRY_PATH=$FOUND_ENTRY_PATH
 	read_entry_path "$ENTRY_PATH"
 fi
 
@@ -1893,7 +1919,7 @@ if [ -n "$ENTRY_ID" ]; then
 				IFS=$OIFS
 				;;
 			esac
-			debug "entry iteration" "$(printf '  >%s<\n' "$@")"
+			[ -z "$DEBUG" ] || debug "entry iteration" "$(printf '  >%s<\n' "$@")"
 			if [ "$first" = "false" ]; then
 				randomize_unit_id
 			fi
@@ -1918,7 +1944,7 @@ if [ -n "$ENTRY_ID" ]; then
 			IFS=$OIFS
 			;;
 		esac
-		debug "entry single" "$(printf '  >%s<\n' "$@")"
+		[ -z "$DEBUG" ] || debug "entry single" "$(printf '  >%s<\n' "$@")"
 		systemd_run "$@"
 		;;
 	esac
@@ -1935,6 +1961,6 @@ else
 		IFS=$OIFS
 		;;
 	esac
-	debug "command" "$(printf '  >%s<\n' "$@")"
+	[ -z "$DEBUG" ] || debug "command" "$(printf '  >%s<\n' "$@")"
 	systemd_run "$@"
 fi
